### ISSUE TITLE
Single-card training configuration error

### ISSUE THREAD

**Issue by AUK1998** [tobran/GALIP#13]
Dear author, your work is very good! I have a problem when I am learning the single card, so I come to ask for help. The error is as follows:  

![3D466338DB9A780B8A41C597E90C8310](https://github.com/tobran/GALIP/assets/148299497/e398f9f0-bfb5-4168-be95-ea8da66659cd)
![DDDFEDA32B39DDC859DE0D3808F46E3B](https://github.com/tobran/GALIP/assets/148299497/87060556-d922-4e08-bc75-5180ec6cb7f4)
Thank you for your answer.

**Comment by AUK1998** [comment]
Error supplement：
![76566695CDA39C8EEB1A4E2348C2E8AD](https://github.com/tobran/GALIP/assets/148299497/d5430e45-7bf4-48c4-bf08-f3df4461c0fe)

**Comment by tobran** [comment]
Hi, there is no problem with the changes you made to single-card training in train.sh. This problem may come from an incorrect version of a package in the environment, or from incorrect settings in the dataloader.
