### ISSUE TITLE
No such file or directory: '../saved_models/pretrained/pre_cc12m.pth'

### ISSUE THREAD

**Issue by kongxy-n** [tobran/GALIP#15]
No such file or directory: '../saved_models/pretrained/pre_cc12m.pth'

When I try the sample , I meet this.

Where can I find this file?

**Comment by tobran** [comment]
Hi, we have provided the pretrained model link in readme (https://drive.google.com/file/d/1VnONvNRjuyHTzuLKBbozZ38-WIt7XZMC/view). You can download it and save it to '../saved_models/pretrained/'.
