### ISSUE TITLE
How many epochs does GALIP need when trained on COCO?

### ISSUE THREAD

**Issue by Di-Zayn** [tobran/GALIP#16]
Hello, I decided to train GALIP on my own GPUs and I found the default epoch number in setup file is 3005. Do I really need that many epochs to get a similar performance to the result in article? Thank you.

**Comment by tobran** [comment]
Hi, thanks to the interest in our work, we trained GALIP on COCO for about 1000epochs (8GPUs, batch size=64). The number of training epochs will vary depending on the number of GPUs and batch size.
