### ISSUE TITLE
Did you train your model by LAION dataset?

### ISSUE THREAD

**Issue by Tangent-Wei** [tobran/GALIP#5]
Hi authors, I really appreciate your opening source code. But it seems that the coco/birds pre-trained models haven't good generalization performance outside the corresponding datasets. I guess the scale of the datasets may be the primary reason, right?

**Comment by tobran** [comment]
Thanks for your interest in our work. The dataset size has a significant influence on generalization performance. We consider training our model on the LAION dataset in future work.
