### ISSUE TITLE
reproduce issue

### ISSUE THREAD

**Issue by taki0112** [tobran/GALIP#9]
Hello. I trained your code on the coco dataset, but it doesn't seem to reproduce correctly. 
Should I set mixed_precision to True? The default value is False, but I'm wondering if it needs to be changed.

The following image is the resulting image obtained after training.
 It is significantly different from the coco image displayed on the main GitHub page.

![image](https://github.com/tobran/GALIP/assets/26713992/2116f09a-5887-45d2-af76-ee60a614fc27)

**Comment by tobran** [comment]
Hi, the default value of mixed_precision is True in our code. You can print the args to check it before training. 
The current training results do not seem to be trained enough, what is the FID of the current result? 
The FID of a sufficiently trained GALIP could be around 5.5. If the current FID is relatively high, you can continue training for some time.
